import subprocess
processo = subprocess.call(["pkg install figlet && figlet Poolz"], shell=True)
escrita = input("oque quer escrever:")
print ('30m":escuro')
print ('31m":vermelho')
print ('32m":verde')
print ('33m":amarelo')
print ('34m":azul')
print ('35m":rosa')
print ('36m":ciano')
print ('37m":branco')
cor = input("qual?")
ass = input ("sua assinatura:")
programa =subprocess.call(['printf "\033[05;'+ cor + " && figlet "+ escrita + " && echo by "+ ass], shell=True)
